"""empty message

Revision ID: 058f111d8676
Revises: bfad8ea58486
Create Date: 2023-05-02 15:48:57.962299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '058f111d8676'
down_revision = 'bfad8ea58486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userotp', schema=None) as batch_op:
        batch_op.alter_column('exp_time',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userotp', schema=None) as batch_op:
        batch_op.alter_column('exp_time',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
