"""empty message

Revision ID: 11ba6f490b3d
Revises: 4677b791ee88
Create Date: 2023-04-17 16:54:23.513294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ba6f490b3d'
down_revision = '4677b791ee88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_admission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('batch', sa.String(length=100), nullable=True),
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_admission')
    # ### end Alembic commands ###
