"""empty message

Revision ID: 3eb66e1f30f1
Revises: 761181c2bd8a
Create Date: 2023-04-20 14:38:22.626343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb66e1f30f1'
down_revision = '761181c2bd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('image', ['image'], unique=False)

    # ### end Alembic commands ###
