"""empty message

Revision ID: 4677b791ee88
Revises: c0895646ed83
Create Date: 2023-04-17 16:51:20.604304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4677b791ee88'
down_revision = 'c0895646ed83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_admission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Total_admission', sa.String(length=100), nullable=True),
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('total_admission')
    # ### end Alembic commands ###
