"""empty message

Revision ID: 761181c2bd8a
Revises: b43fa0b7c879
Create Date: 2023-04-20 14:36:11.477885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '761181c2bd8a'
down_revision = 'b43fa0b7c879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
