"""empty message

Revision ID: 7f5e5e37e5a5
Revises: f21a301c02e2
Create Date: 2023-04-06 14:26:51.620742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5e5e37e5a5'
down_revision = 'f21a301c02e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
