"""empty message

Revision ID: b43fa0b7c879
Revises: dcd97acf49ca
Create Date: 2023-04-20 14:05:24.639685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43fa0b7c879'
down_revision = 'dcd97acf49ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_name', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pic_name')

    # ### end Alembic commands ###
