"""empty message

Revision ID: f21a301c02e2
Revises: 0c2b817ff532
Create Date: 2023-04-06 12:47:36.198436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f21a301c02e2'
down_revision = '0c2b817ff532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('empolyee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empolyee_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
